import { cac, type CAC } from "cac";
import { createElement as h, type ReactNode } from "react";
import { tokenize } from "@/pages/terminal/shell";
import { CAREER_LINES } from "@/pages/terminal/data/career";
import { PROJECTS, findProject } from "@/pages/terminal/data/projects";

/**
 * CLI engine for the /terminal fork (terminal.md §cli) — cac owns ALL
 * dispatch: commands are registered declaratively via `cli.command(...)`
 * and matched by `cli.parse`; there is deliberately no switch/if command
 * routing here. cac is browser-safe at module scope (it guards
 * `typeof process`), and `cli.help()` / `cli.version()` are never called —
 * those print via console. Instead `help` is a real command whose output is
 * GENERATED by iterating `cli.commands`.
 *
 * (.ts + createElement instead of JSX: the engine stays UI-agnostic logic —
 * emitted nodes are plain element trees.)
 */

export interface ShellDeps {
  /** append one output node to the REPL history */
  emit: (node: ReactNode) => void;
  /** react-router navigate — used by `open` */
  navigate: (path: string) => void;
  /** wipe the REPL history — used by `clear` */
  clear: () => void;
}

export interface Shell {
  run(input: string): Promise<void>;
  /** stable Tab-completion candidates: command names + paths + project names */
  candidates: string[];
}

/** one dim output line */
const line = (text: string, className = "text-dim") =>
  h("div", { className: `whitespace-pre-wrap ${className}` }, text);

export function createShell({ emit, navigate, clear }: ShellDeps): Shell {
  function buildCli(): CAC {
    const cli = cac("yii");

    cli.command("help", "show this usage table").action(() => {
      // generated from the registry — never a hardcoded command list
      const rows = cli.commands.map((cmd) => `  ${cmd.rawName.padEnd(16)} ${cmd.description}`);
      emit(
        h(
          "pre",
          { className: "whitespace-pre-wrap text-ash" },
          ["usage: <command> [args]", "", ...rows].join("\n"),
        ),
      );
    });

    cli.command("ls [path]", "list a directory — career/ projects/").action((path?: string) => {
      if (!path || path === "." || path === "~") {
        emit(
          h(
            "div",
            { className: "flex gap-6" },
            h("span", { className: "text-wasi-cyan" }, "career/"),
            h("span", { className: "text-wasi-cyan" }, "projects/"),
          ),
        );
        return;
      }
      if (path === "career" || path === "career/") {
        // pure-text git log derived from COMMITS (@/pages/home/log-data)
        emit(h("pre", { className: "whitespace-pre-wrap text-ash" }, CAREER_LINES.join("\n")));
        return;
      }
      if (path === "projects" || path === "projects/") {
        emit(
          h(
            "pre",
            { className: "whitespace-pre-wrap text-ash" },
            PROJECTS.map((p) => `${p.name.padEnd(12)} ${p.tagline}`).join("\n"),
          ),
        );
        return;
      }
      emit(line(`ls: ${path}: No such file or directory`));
    });

    cli.command("show <name>", "show project details").action((name: string) => {
      const p = findProject(name);
      if (!p) {
        emit(line(`show: no such project: ${name}`));
        return;
      }
      emit(
        h(
          "div",
          { className: "flex flex-col gap-1" },
          h(
            "div",
            null,
            h("span", { className: "text-bone" }, p.name),
            h("span", { className: "text-ash" }, ` — ${p.tagline}`),
          ),
          h("div", { className: "max-w-2xl text-dim" }, p.description),
          h(
            "div",
            { className: "mt-1 flex flex-wrap gap-x-4 gap-y-1" },
            ...p.facts.map((f) =>
              f.href
                ? h(
                    "a",
                    {
                      key: f.label,
                      href: f.href,
                      target: "_blank",
                      rel: "noreferrer",
                      className: "text-halo underline",
                    },
                    f.label,
                  )
                : h("span", { key: f.label, className: "text-ash" }, f.label),
            ),
          ),
        ),
      );
    });

    cli.command("open <name>", "open a project's terminal page").action((name: string) => {
      const p = findProject(name);
      if (!p) {
        emit(line(`open: no such project: ${name}`));
        return;
      }
      if (p.route) {
        navigate(p.route);
        return;
      }
      // no fork page (thatyii.dev IS this site) — point at the live URL
      const url = p.facts.find((f) => f.href)?.href;
      emit(line(`${p.name} has no fork page${url ? ` — it's live at ${url}` : ""}`));
    });

    cli.command("clear", "clear the terminal").action(() => clear());

    return cli;
  }

  async function run(input: string): Promise<void> {
    const tokens = tokenize(input);
    if (tokens.length === 0) return;
    // Fresh instance per run: cac keeps matchedCommand state across parses,
    // and a stale match would re-fire on the next unmatched input.
    const cli = buildCli();
    try {
      cli.parse(["", "", ...tokens], { run: false });
      if (!cli.matchedCommand) {
        emit(line(`zsh: command not found: ${tokens[0]}`));
        return;
      }
      // throws CACError on unknown options / missing args — emitted as output
      await cli.runMatchedCommand();
    } catch (err) {
      emit(line(err instanceof Error ? err.message : String(err)));
    }
  }

  // Static command tree — built ONCE as the stable candidate list. Only `run`
  // needs a fresh instance per call (cac keeps matchedCommand state across
  // parses), so completion never rebuilds the tree.
  const candidates: string[] = [
    ...buildCli().commands.map((cmd) => cmd.name),
    "career",
    "projects",
    ...PROJECTS.map((p) => p.name),
  ];

  return { run, candidates };
}
